[package]
name = "yggdrasil-prototype"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atspi={git="https://github.com/yggdrasil-sr/atspi-rs.git"}
once_cell = "1.8.0"
tts_subsystem={git="https://github.com/yggdrasil-sr/tts_subsystem.git"}

[features]
